// src/app/layout.js
import "bootstrap/dist/css/bootstrap.min.css";
import "./style/admin.css";
import { Header } from "@/components/Header";
import { Sidebar } from "@/components/Sidebar";
import { Footer } from "@/components/Footer";
import { AppProvider } from "@/context/AppContext";
import { AuthProvider } from "@/context/AuthContext"; // Import AuthContext

export const metadata = {
  title: "QR ",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container-fluid">
          {/* Wrap everything with AuthProvider to provide authentication data */}
          <AuthProvider>
            <Header />
            <div className="d-flex">
              <Sidebar />
              <AppProvider>
                <main className="main-content">{children}</main>
              </AppProvider>
            </div>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
