// src/app/layout.js
import "bootstrap/dist/css/bootstrap.min.css";
import "./style/admin.css";
import { Header } from "@/components/Header";
import { Sidebar } from "@/components/Sidebar";
import { Footer } from "@/components/Footer";
import { AppProvider } from "@/context/AppContext";

export const metadata = {
  title: "Event",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container-fluid">
          <Header />
          <div className="d-flex">
            <Sidebar />
            <AppProvider>
              <main className="main-content">{children}</main>
            </AppProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
